server:
  port: 29003
spring:
  application:
    name: EMISpringBoot-expressDelivery
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
#    password: root
    password: hzyNB@@
    url: jdbc:mysql://1.12.75.55:3306/EMI-express-delivery?characterEncoding=utf-8&useSSL=false&useTimezone=Asia/Shanghai
#    url: jdbc:mariadb://192.168.66.133:3306/EMI-express-delivery?characterEncoding=utf-8&useSSL=false&useTimezone=true
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
  cloud:
    nacos:
      discovery:
        server-addr: 1.12.75.55:8848
        ip: localhost
        port: 29003
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: EMISpringBoot.model.expressDelivery
#  global-config:
#    datacenter-id: 1
#    workerId: 1
#  #mapper.xml文件中resultType的type或者paramterType会返回自定义entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志
