server:
  port: 26001
spring:
  application:
    name: EMISpringBoot-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 1.12.75.55:8848
        ip: localhost
        port: 26001
    gateway:
      globalcors: # 全局的跨域处理
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        corsConfigurations:
          '[/**]':
            allowedOrigins: # 允许哪些网站的跨域请求
              - "*"
            allowedMethods: # 允许的跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: # 允许在请求中携带的头信息
              - "*"
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000 # 这次跨域检测的有效期
      routes:
        # 管理员登录
        - id: admin
          uri: lb://EMISpringBoot-admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
            - PrefixPath=/api
        # 订单编辑
        - id: expressDelivery
          uri: lb://EMISpringBoot-expressDelivery
          predicates:
            - Path=/expressDelivery/**
          filters:
            - StripPrefix= 1
            - PrefixPath=/api
        # 用户登录
        - id: customerUser
          uri: lb://EMISpringBoot-CustomerUser
          predicates:
            - Path=/customerUser/**
          filters:
            - StripPrefix= 1
            - PrefixPath=/api